### ISSUE TITLE
database notifcation with c vis error

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker7ExternalDevicesPlugin#1]
When you try running a script which uses a external notification protocol set up, but forget to set up the external device, the system runs though warning about not getting a notifcation database ack, but carries on running (this is fine) but when stop kicks off, itll crash with a connection refused error instead of ignoring or warning about the lost connection

**Comment by andrewgait** [comment]
Think I've fixed this with https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/169 ?

**Comment by alan-stokes** [comment]
tested with spike io interfactive demo with c vis with multi run and resets between. works. so think this issue is closed.
